package com.lims.domain.po;

import java.util.Date;

import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

public class AnalysisRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ANALYSIS_RECORD.ID
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    private String id;

    private String boardInfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ANALYSIS_RECORD.ANALYSIS_DATE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    private Date analysisDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ANALYSIS_RECORD.ANALYSIS_INSTRUMENT
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    private String analysisInstrument;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ANALYSIS_RECORD.CREATE_DATE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ANALYSIS_RECORD.CREATE_USER
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ANALYSIS_RECORD.REMARK
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    private String remark;

    private String updateUser;

    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ANALYSIS_RECORD.ID
     *
     * @return the value of ANALYSIS_RECORD.ID
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ANALYSIS_RECORD.ID
     *
     * @param id the value for ANALYSIS_RECORD.ID
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ANALYSIS_RECORD.ANALYSIS_DATE
     *
     * @return the value of ANALYSIS_RECORD.ANALYSIS_DATE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public Date getAnalysisDate() {
        return analysisDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ANALYSIS_RECORD.ANALYSIS_DATE
     *
     * @param analysisDate the value for ANALYSIS_RECORD.ANALYSIS_DATE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setAnalysisDate(Date analysisDate) {
        this.analysisDate = analysisDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ANALYSIS_RECORD.ANALYSIS_INSTRUMENT
     *
     * @return the value of ANALYSIS_RECORD.ANALYSIS_INSTRUMENT
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public String getAnalysisInstrument() {
        return analysisInstrument;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ANALYSIS_RECORD.ANALYSIS_INSTRUMENT
     *
     * @param analysisInstrument the value for ANALYSIS_RECORD.ANALYSIS_INSTRUMENT
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setAnalysisInstrument(String analysisInstrument) {
        this.analysisInstrument = analysisInstrument;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ANALYSIS_RECORD.CREATE_DATE
     *
     * @return the value of ANALYSIS_RECORD.CREATE_DATE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ANALYSIS_RECORD.CREATE_DATE
     *
     * @param createDate the value for ANALYSIS_RECORD.CREATE_DATE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ANALYSIS_RECORD.CREATE_USER
     *
     * @return the value of ANALYSIS_RECORD.CREATE_USER
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ANALYSIS_RECORD.CREATE_USER
     *
     * @param createUser the value for ANALYSIS_RECORD.CREATE_USER
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ANALYSIS_RECORD.REMARK
     *
     * @return the value of ANALYSIS_RECORD.REMARK
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ANALYSIS_RECORD.REMARK
     *
     * @param remark the value for ANALYSIS_RECORD.REMARK
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

	@Override
	public String toString() {
		return ToStringBuilder.reflectionToString(this, ToStringStyle.MULTI_LINE_STYLE);
	}

	public String getBoardInfoId() {
		return boardInfoId;
	}

	public void setBoardInfoId(String boardInfoId) {
		this.boardInfoId = boardInfoId;
	}

	public String getUpdateUser() {
		return updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	public Date getUpdateDate() {
		return updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}
}