package com.lims.domain.po;

import java.io.Serializable;
import java.util.Date;

import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

public class BoardInfo extends BaseDomain implements Serializable {
    /**
	 *
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOARD_INFO.ID
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    protected String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOARD_INFO.BOARD_NAME
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    protected String boardName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOARD_INFO.BOARD_NO
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    protected String boardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOARD_INFO.CONSIGMENT_ID
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    protected String consignmentNo;

    protected String consignmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOARD_INFO.WORKSTATION_FILENAME
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    protected String workstationFilename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOARD_INFO.BARCODELESS_NUM
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    protected String barcodelessNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOARD_INFO.SAMPLELESS_NUM
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    protected String samplelessNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOARD_INFO.HOLE_DIAMETER
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    protected String holeDiameter;


    protected String[] holeDiameterArr;

    protected String holeDiameterOther;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOARD_INFO.EXAMINE_TYPE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    protected String examineType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOARD_INFO.EXAMINE_STATUS
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    protected String examineStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOARD_INFO.EXAMINE_DATE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    protected Date examineDate;

    protected String examineUser;

    protected String pcrFlag;

    protected String analysisFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOARD_INFO.IMPORT_DATE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    protected Date importDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOARD_INFO.IMPORT_USER
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    protected String importUser;
    protected String importUserName;

    protected String examineInstrumentNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOARD_INFO.UPDATE_DATE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    protected Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOARD_INFO.UPDATE_USER
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    protected String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOARD_INFO.REMARK
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    protected String remark;

    protected String reviewStatus;

    protected String reviewUser;

    protected String reviewDate;

    protected String generateRecordFlag;

    protected Date generateRecordDate;

    protected String generateSyTableFlag;

    protected Date generateSyTableDate;

    protected String importResultFlag;

    protected Date importResultDate;

    protected int examineRecordDownloadCnt;

    protected int syrecordDownloadCnt;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BOARD_INFO.ID
     *
     * @return the value of BOARD_INFO.ID
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BOARD_INFO.ID
     *
     * @param id the value for BOARD_INFO.ID
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BOARD_INFO.BOARD_NAME
     *
     * @return the value of BOARD_INFO.BOARD_NAME
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public String getBoardName() {
        return boardName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BOARD_INFO.BOARD_NAME
     *
     * @param boardName the value for BOARD_INFO.BOARD_NAME
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setBoardName(String boardName) {
        this.boardName = boardName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BOARD_INFO.BOARD_NO
     *
     * @return the value of BOARD_INFO.BOARD_NO
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public String getBoardNo() {
        return boardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BOARD_INFO.BOARD_NO
     *
     * @param boardNo the value for BOARD_INFO.BOARD_NO
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setBoardNo(String boardNo) {
        this.boardNo = boardNo;
    }



    public String getConsignmentNo() {
		return consignmentNo;
	}

	public void setConsignmentNo(String consignmentNo) {
		this.consignmentNo = consignmentNo;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BOARD_INFO.WORKSTATION_FILENAME
     *
     * @return the value of BOARD_INFO.WORKSTATION_FILENAME
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public String getWorkstationFilename() {
        return workstationFilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BOARD_INFO.WORKSTATION_FILENAME
     *
     * @param workstationFilename the value for BOARD_INFO.WORKSTATION_FILENAME
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setWorkstationFilename(String workstationFileName) {
        this.workstationFilename = workstationFileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BOARD_INFO.HOLE_DIAMETER
     *
     * @return the value of BOARD_INFO.HOLE_DIAMETER
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public String getHoleDiameter() {
        return holeDiameter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BOARD_INFO.HOLE_DIAMETER
     *
     * @param holeDiameter the value for BOARD_INFO.HOLE_DIAMETER
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setHoleDiameter(String holeDiameter) {
        this.holeDiameter = holeDiameter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BOARD_INFO.EXAMINE_TYPE
     *
     * @return the value of BOARD_INFO.EXAMINE_TYPE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public String getExamineType() {
        return examineType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BOARD_INFO.EXAMINE_TYPE
     *
     * @param examineType the value for BOARD_INFO.EXAMINE_TYPE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setExamineType(String examineType) {
        this.examineType = examineType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BOARD_INFO.EXAMINE_STATUS
     *
     * @return the value of BOARD_INFO.EXAMINE_STATUS
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public String getExamineStatus() {
        return examineStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BOARD_INFO.EXAMINE_STATUS
     *
     * @param examineStatus the value for BOARD_INFO.EXAMINE_STATUS
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setExamineStatus(String examineStatus) {
        this.examineStatus = examineStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BOARD_INFO.EXAMINE_DATE
     *
     * @return the value of BOARD_INFO.EXAMINE_DATE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public Date getExamineDate() {
        return examineDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BOARD_INFO.EXAMINE_DATE
     *
     * @param examineDate the value for BOARD_INFO.EXAMINE_DATE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setExamineDate(Date examineDate) {
        this.examineDate = examineDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BOARD_INFO.IMPORT_DATE
     *
     * @return the value of BOARD_INFO.IMPORT_DATE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public Date getImportDate() {
        return importDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BOARD_INFO.IMPORT_DATE
     *
     * @param importDate the value for BOARD_INFO.IMPORT_DATE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setImportDate(Date importDate) {
        this.importDate = importDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BOARD_INFO.IMPORT_USER
     *
     * @return the value of BOARD_INFO.IMPORT_USER
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public String getImportUser() {
        return importUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BOARD_INFO.IMPORT_USER
     *
     * @param importUser the value for BOARD_INFO.IMPORT_USER
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setImportUser(String importUser) {
        this.importUser = importUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BOARD_INFO.UPDATE_DATE
     *
     * @return the value of BOARD_INFO.UPDATE_DATE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BOARD_INFO.UPDATE_DATE
     *
     * @param updateDate the value for BOARD_INFO.UPDATE_DATE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BOARD_INFO.UPDATE_USER
     *
     * @return the value of BOARD_INFO.UPDATE_USER
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BOARD_INFO.UPDATE_USER
     *
     * @param updateUser the value for BOARD_INFO.UPDATE_USER
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BOARD_INFO.REMARK
     *
     * @return the value of BOARD_INFO.REMARK
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BOARD_INFO.REMARK
     *
     * @param remark the value for BOARD_INFO.REMARK
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    @Override
	public String toString() {
		return ToStringBuilder.reflectionToString(this, ToStringStyle.MULTI_LINE_STYLE);
	}

	public String getImportUserName() {
		return importUserName;
	}

	public void setImportUserName(String importUserName) {
		this.importUserName = importUserName;
	}

	public String getPcrFlag() {
		return pcrFlag;
	}

	public void setPcrFlag(String pcrFlag) {
		this.pcrFlag = pcrFlag;
	}

	public String getAnalysisFlag() {
		return analysisFlag;
	}

	public void setAnalysisFlag(String analysisFlag) {
		this.analysisFlag = analysisFlag;
	}

	public String getExamineUser() {
		return examineUser;
	}

	public void setExamineUser(String examineUser) {
		this.examineUser = examineUser;
	}

	public String getHoleDiameterOther() {
		return holeDiameterOther;
	}

	public void setHoleDiameterOther(String holeDiameterOther) {
		this.holeDiameterOther = holeDiameterOther;
	}

	public String getReviewStatus() {
		return reviewStatus;
	}

	public void setReviewStatus(String reviewStatus) {
		this.reviewStatus = reviewStatus;
	}

	public String getReviewUser() {
		return reviewUser;
	}

	public void setReviewUser(String reviewUser) {
		this.reviewUser = reviewUser;
	}

	public String getReviewDate() {
		return reviewDate;
	}

	public void setReviewDate(String reviewDate) {
		this.reviewDate = reviewDate;
	}

	public String getBarcodelessNum() {
		return barcodelessNum;
	}

	public void setBarcodelessNum(String barcodelessNum) {
		this.barcodelessNum = barcodelessNum;
	}

	public String getSamplelessNum() {
		return samplelessNum;
	}

	public void setSamplelessNum(String samplelessNum) {
		this.samplelessNum = samplelessNum;
	}

	public String[] getHoleDiameterArr() {
		return holeDiameterArr;
	}

	public void setHoleDiameterArr(String[] holeDiameterArr) {
		this.holeDiameterArr = holeDiameterArr;
	}

	public String getConsignmentId() {
		return consignmentId;
	}

	public void setConsignmentId(String consignmentId) {
		this.consignmentId = consignmentId;
	}

	public String getExamineInstrumentNo() {
		return examineInstrumentNo;
	}

	public void setExamineInstrumentNo(String examineInstrumentNo) {
		this.examineInstrumentNo = examineInstrumentNo;
	}

	public String getGenerateRecordFlag() {
		return generateRecordFlag;
	}

	public void setGenerateRecordFlag(String generateRecordFlag) {
		this.generateRecordFlag = generateRecordFlag;
	}

	public Date getGenerateRecordDate() {
		return generateRecordDate;
	}

	public void setGenerateRecordDate(Date generateRecordDate) {
		this.generateRecordDate = generateRecordDate;
	}

	public String getGenerateSyTableFlag() {
		return generateSyTableFlag;
	}

	public void setGenerateSyTableFlag(String generateSyTableFlag) {
		this.generateSyTableFlag = generateSyTableFlag;
	}

	public Date getGenerateSyTableDate() {
		return generateSyTableDate;
	}

	public void setGenerateSyTableDate(Date generateSyTableDate) {
		this.generateSyTableDate = generateSyTableDate;
	}

	public String getImportResultFlag() {
		return importResultFlag;
	}

	public void setImportResultFlag(String importResultFlag) {
		this.importResultFlag = importResultFlag;
	}

	public Date getImportResultDate() {
		return importResultDate;
	}

	public void setImportResultDate(Date importResultDate) {
		this.importResultDate = importResultDate;
	}

	public int getExamineRecordDownloadCnt() {
		return examineRecordDownloadCnt;
	}

	public void setExamineRecordDownloadCnt(int examineRecordDownloadCnt) {
		this.examineRecordDownloadCnt = examineRecordDownloadCnt;
	}

	public int getSyrecordDownloadCnt() {
		return syrecordDownloadCnt;
	}

	public void setSyrecordDownloadCnt(int syrecordDownloadCnt) {
		this.syrecordDownloadCnt = syrecordDownloadCnt;
	}
}