package com.lims.domain.po;

import java.io.Serializable;
import java.util.Date;

import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

public class BoardSampleMap extends BaseDomain implements Serializable {
    /**
	 *
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOARD_SAMPLE_MAP.ID
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    protected String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOARD_SAMPLE_MAP.BOARD_ID
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    protected String boardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOARD_SAMPLE_MAP.SAMPLE_ID
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    protected String sampleId;
    protected String sampleNo;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOARD_SAMPLE_MAP.SAMPLE_POSITION
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    protected String samplePosition;

    protected String extractUser;
    protected String extractUserName;

    protected Date extractDate;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BOARD_SAMPLE_MAP.ID
     *
     * @return the value of BOARD_SAMPLE_MAP.ID
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BOARD_SAMPLE_MAP.ID
     *
     * @param id the value for BOARD_SAMPLE_MAP.ID
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BOARD_SAMPLE_MAP.BOARD_ID
     *
     * @return the value of BOARD_SAMPLE_MAP.BOARD_ID
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public String getBoardId() {
        return boardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BOARD_SAMPLE_MAP.BOARD_ID
     *
     * @param boardId the value for BOARD_SAMPLE_MAP.BOARD_ID
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setBoardId(String boardId) {
        this.boardId = boardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BOARD_SAMPLE_MAP.SAMPLE_ID
     *
     * @return the value of BOARD_SAMPLE_MAP.SAMPLE_ID
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public String getSampleId() {
        return sampleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BOARD_SAMPLE_MAP.SAMPLE_ID
     *
     * @param sampleId the value for BOARD_SAMPLE_MAP.SAMPLE_ID
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setSampleId(String sampleId) {
        this.sampleId = sampleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BOARD_SAMPLE_MAP.SAMPLE_POSITION
     *
     * @return the value of BOARD_SAMPLE_MAP.SAMPLE_POSITION
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public String getSamplePosition() {
        return samplePosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BOARD_SAMPLE_MAP.SAMPLE_POSITION
     *
     * @param samplePosition the value for BOARD_SAMPLE_MAP.SAMPLE_POSITION
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setSamplePosition(String samplePosition) {
        this.samplePosition = samplePosition;
    }

    @Override
	public String toString() {
		return ToStringBuilder.reflectionToString(this, ToStringStyle.MULTI_LINE_STYLE);
	}

	public String getSampleNo() {
		return sampleNo;
	}

	public void setSampleNo(String sampleNo) {
		this.sampleNo = sampleNo;
	}

	public String getExtractUser() {
		return extractUser;
	}

	public void setExtractUser(String extractUser) {
		this.extractUser = extractUser;
	}

	public String getExtractUserName() {
		return extractUserName;
	}

	public void setExtractUserName(String extractUserName) {
		this.extractUserName = extractUserName;
	}

	public Date getExtractDate() {
		return extractDate;
	}

	public void setExtractDate(Date extractDate) {
		this.extractDate = extractDate;
	}
}