package com.lims.domain.po;

import java.io.Serializable;
import java.util.Date;

import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

public class Consignment extends BaseDomain implements Serializable {
    /**
	 *
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSIGNMENT.ID
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    protected String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSIGNMENT.CONSIGNMENT_NO
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    protected String consignmentNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSIGNMENT.ORGANIZATION_ID
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    protected String organizationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSIGNMENT.ORGANIZATION_SUB_NAME
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    protected String organizationSubName;

    /**
     * 委托时间
     */
    protected Date consignDate;

    /**
     * 委托联系人
     */
    protected String consignmentor;

    /**
     * 联系电话
     */
    protected String phonenum;

    /**
     * 送检方式
     */
    protected String consignMethod;

    /**
     * 送检样本类型
     */
    protected String consignSampleType;


    /**
     * 送检样本份数
     */
    protected String consignSampleCount;

    protected String consignBloodCount;
    protected String consignSalivaCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSIGNMENT.CHECK_CONTENT_TYPE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    protected String checkContentType;

    /**
     * 样本载体
     */
    protected String sampleCarrier;

    /**
     * 样本载体说明
     */
    protected String sampleCarrierDesc;

    protected String sampleCarrierOther;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSIGNMENT.AGREEMENT_AMOUNT
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    protected String agreementAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSIGNMENT.EXPENSE_BALANCE_DATE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    protected Date expenseBalanceDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSIGNMENT.DATA_UPLOAD_DATE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    protected Date dataUploadDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSIGNMENT.SAMPLE_REBACK_DATE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    protected Date sampleRebackDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSIGNMENT.REMARK
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    protected String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSIGNMENT.CREATE_DATE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    protected Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSIGNMENT.CREATE_USER
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    protected String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSIGNMENT.UPDATE_DATE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    protected Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSIGNMENT.UPDATE_USER
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    protected String updateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSIGNMENT.ID
     *
     * @return the value of CONSIGNMENT.ID
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSIGNMENT.ID
     *
     * @param id the value for CONSIGNMENT.ID
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSIGNMENT.CONSIGNMENT_NO
     *
     * @return the value of CONSIGNMENT.CONSIGNMENT_NO
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public String getConsignmentNo() {
        return consignmentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSIGNMENT.CONSIGNMENT_NO
     *
     * @param consignmentNo the value for CONSIGNMENT.CONSIGNMENT_NO
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setConsignmentNo(String consignmentNo) {
        this.consignmentNo = consignmentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSIGNMENT.ORGANIZATION_ID
     *
     * @return the value of CONSIGNMENT.ORGANIZATION_ID
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public String getOrganizationId() {
        return organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSIGNMENT.ORGANIZATION_ID
     *
     * @param organizationId the value for CONSIGNMENT.ORGANIZATION_ID
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setOrganizationId(String organizationId) {
        this.organizationId = organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSIGNMENT.ORGANIZATION_SUB_NAME
     *
     * @return the value of CONSIGNMENT.ORGANIZATION_SUB_NAME
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public String getOrganizationSubName() {
        return organizationSubName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSIGNMENT.ORGANIZATION_SUB_NAME
     *
     * @param organizationSubName the value for CONSIGNMENT.ORGANIZATION_SUB_NAME
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setOrganizationSubName(String organizationSubName) {
        this.organizationSubName = organizationSubName;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSIGNMENT.CONSIGNMENTOR
     *
     * @return the value of CONSIGNMENT.CONSIGNMENTOR
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public String getConsignmentor() {
        return consignmentor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSIGNMENT.CONSIGNMENTOR
     *
     * @param consignmentor the value for CONSIGNMENT.CONSIGNMENTOR
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setConsignmentor(String consignmentor) {
        this.consignmentor = consignmentor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSIGNMENT.PHONENUM
     *
     * @return the value of CONSIGNMENT.PHONENUM
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public String getPhonenum() {
        return phonenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSIGNMENT.PHONENUM
     *
     * @param phonenum the value for CONSIGNMENT.PHONENUM
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setPhonenum(String phonenum) {
        this.phonenum = phonenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSIGNMENT.CHECK_CONTENT_TYPE
     *
     * @return the value of CONSIGNMENT.CHECK_CONTENT_TYPE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public String getCheckContentType() {
        return checkContentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSIGNMENT.CHECK_CONTENT_TYPE
     *
     * @param checkContentType the value for CONSIGNMENT.CHECK_CONTENT_TYPE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setCheckContentType(String checkContentType) {
        this.checkContentType = checkContentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSIGNMENT.SAMPLE_CARRIER
     *
     * @return the value of CONSIGNMENT.SAMPLE_CARRIER
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public String getSampleCarrier() {
        return sampleCarrier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSIGNMENT.SAMPLE_CARRIER
     *
     * @param sampleCarrier the value for CONSIGNMENT.SAMPLE_CARRIER
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setSampleCarrier(String sampleCarrier) {
        this.sampleCarrier = sampleCarrier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSIGNMENT.SAMPLE_CARRIER_DESC
     *
     * @return the value of CONSIGNMENT.SAMPLE_CARRIER_DESC
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public String getSampleCarrierDesc() {
        return sampleCarrierDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSIGNMENT.SAMPLE_CARRIER_DESC
     *
     * @param sampleCarrierDesc the value for CONSIGNMENT.SAMPLE_CARRIER_DESC
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setSampleCarrierDesc(String sampleCarrierDesc) {
        this.sampleCarrierDesc = sampleCarrierDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSIGNMENT.AGREEMENT_AMOUNT
     *
     * @return the value of CONSIGNMENT.AGREEMENT_AMOUNT
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public String getAgreementAmount() {
        return agreementAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSIGNMENT.AGREEMENT_AMOUNT
     *
     * @param agreementAmount the value for CONSIGNMENT.AGREEMENT_AMOUNT
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setAgreementAmount(String agreementAmount) {
        this.agreementAmount = agreementAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSIGNMENT.EXPENSE_BALANCE_DATE
     *
     * @return the value of CONSIGNMENT.EXPENSE_BALANCE_DATE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public Date getExpenseBalanceDate() {
        return expenseBalanceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSIGNMENT.EXPENSE_BALANCE_DATE
     *
     * @param expenseBalanceDate the value for CONSIGNMENT.EXPENSE_BALANCE_DATE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setExpenseBalanceDate(Date expenseBalanceDate) {
        this.expenseBalanceDate = expenseBalanceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSIGNMENT.DATA_UPLOAD_DATE
     *
     * @return the value of CONSIGNMENT.DATA_UPLOAD_DATE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public Date getDataUploadDate() {
        return dataUploadDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSIGNMENT.DATA_UPLOAD_DATE
     *
     * @param dataUploadDate the value for CONSIGNMENT.DATA_UPLOAD_DATE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setDataUploadDate(Date dataUploadDate) {
        this.dataUploadDate = dataUploadDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSIGNMENT.SAMPLE_REBACK_DATE
     *
     * @return the value of CONSIGNMENT.SAMPLE_REBACK_DATE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public Date getSampleRebackDate() {
        return sampleRebackDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSIGNMENT.SAMPLE_REBACK_DATE
     *
     * @param sampleRebackDate the value for CONSIGNMENT.SAMPLE_REBACK_DATE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setSampleRebackDate(Date sampleRebackDate) {
        this.sampleRebackDate = sampleRebackDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSIGNMENT.REMARK
     *
     * @return the value of CONSIGNMENT.REMARK
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSIGNMENT.REMARK
     *
     * @param remark the value for CONSIGNMENT.REMARK
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSIGNMENT.CREATE_DATE
     *
     * @return the value of CONSIGNMENT.CREATE_DATE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSIGNMENT.CREATE_DATE
     *
     * @param createDate the value for CONSIGNMENT.CREATE_DATE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSIGNMENT.CREATE_USER
     *
     * @return the value of CONSIGNMENT.CREATE_USER
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSIGNMENT.CREATE_USER
     *
     * @param createUser the value for CONSIGNMENT.CREATE_USER
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSIGNMENT.UPDATE_DATE
     *
     * @return the value of CONSIGNMENT.UPDATE_DATE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSIGNMENT.UPDATE_DATE
     *
     * @param updateDate the value for CONSIGNMENT.UPDATE_DATE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSIGNMENT.UPDATE_USER
     *
     * @return the value of CONSIGNMENT.UPDATE_USER
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSIGNMENT.UPDATE_USER
     *
     * @param updateUser the value for CONSIGNMENT.UPDATE_USER
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    @Override
	public String toString() {
		return ToStringBuilder.reflectionToString(this, ToStringStyle.MULTI_LINE_STYLE);
	}

	public Date getConsignDate() {
		return consignDate;
	}

	public void setConsignDate(Date consignDate) {
		this.consignDate = consignDate;
	}

	public String getConsignMethod() {
		return consignMethod;
	}

	public void setConsignMethod(String consignMethod) {
		this.consignMethod = consignMethod;
	}

	public String getConsignSampleType() {
		return consignSampleType;
	}

	public void setConsignSampleType(String consignSampleType) {
		this.consignSampleType = consignSampleType;
	}

	public String getConsignSampleCount() {
		return consignSampleCount;
	}

	public void setConsignSampleCount(String consignSampleCount) {
		this.consignSampleCount = consignSampleCount;
	}

	public String getConsignBloodCount() {
		return consignBloodCount;
	}

	public void setConsignBloodCount(String consignBloodCount) {
		this.consignBloodCount = consignBloodCount;
	}

	public String getConsignSalivaCount() {
		return consignSalivaCount;
	}

	public void setConsignSalivaCount(String consignSalivaCount) {
		this.consignSalivaCount = consignSalivaCount;
	}

	public String getSampleCarrierOther() {
		return sampleCarrierOther;
	}

	public void setSampleCarrierOther(String sampleCarrierOther) {
		this.sampleCarrierOther = sampleCarrierOther;
	}

}