package com.lims.domain.po;

import java.io.Serializable;
import java.util.Date;

import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

/**
 * 委托单位
 *
 * @author lizhihua
 *
 */
public class ConsignOrganization extends BaseDomain implements Serializable {


    /**
	 *
	 */
	private static final long serialVersionUID = 1L;



	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSIGN_ORGANIZATION.ID
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    private String id;

    /**
     *
     * 行政区划编码
     *
     */
    private String organizationCode;

    /**
     *
     * 行政区划名称
     *
     */
    private String organizationName;

    /**
     *
     * 上级ID
     *
     */
    private String parentOrganizationId;

    /**
     *
     * 单位地址
     *
     */
    private String organizationAddress;

    /**
     *
     * 联系电话
     *
     */
    private String phonenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSIGN_ORGANIZATION.POSTCODE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    private String postcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSIGN_ORGANIZATION.CREATE_DATE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSIGN_ORGANIZATION.CREATE_USER
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSIGN_ORGANIZATION.UPDATE_DATE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSIGN_ORGANIZATION.UPDATE_USER
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSIGN_ORGANIZATION.REMARK
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSIGN_ORGANIZATION.ID
     *
     * @return the value of CONSIGN_ORGANIZATION.ID
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSIGN_ORGANIZATION.ID
     *
     * @param id the value for CONSIGN_ORGANIZATION.ID
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSIGN_ORGANIZATION.ORGANIZATION_CODE
     *
     * @return the value of CONSIGN_ORGANIZATION.ORGANIZATION_CODE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public String getOrganizationCode() {
        return organizationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSIGN_ORGANIZATION.ORGANIZATION_CODE
     *
     * @param organizationCode the value for CONSIGN_ORGANIZATION.ORGANIZATION_CODE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setOrganizationCode(String organizationCode) {
        this.organizationCode = organizationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSIGN_ORGANIZATION.ORGANIZATION_NAME
     *
     * @return the value of CONSIGN_ORGANIZATION.ORGANIZATION_NAME
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public String getOrganizationName() {
        return organizationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSIGN_ORGANIZATION.ORGANIZATION_NAME
     *
     * @param organizationName the value for CONSIGN_ORGANIZATION.ORGANIZATION_NAME
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setOrganizationName(String organizationName) {
        this.organizationName = organizationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSIGN_ORGANIZATION.PARENT_ORGANIZATION_ID
     *
     * @return the value of CONSIGN_ORGANIZATION.PARENT_ORGANIZATION_ID
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public String getParentOrganizationId() {
        return parentOrganizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSIGN_ORGANIZATION.PARENT_ORGANIZATION_ID
     *
     * @param parentOrganizationId the value for CONSIGN_ORGANIZATION.PARENT_ORGANIZATION_ID
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setParentOrganizationId(String parentOrganizationId) {
        this.parentOrganizationId = parentOrganizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSIGN_ORGANIZATION.ORGANIZATION_ADDRESS
     *
     * @return the value of CONSIGN_ORGANIZATION.ORGANIZATION_ADDRESS
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public String getOrganizationAddress() {
        return organizationAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSIGN_ORGANIZATION.ORGANIZATION_ADDRESS
     *
     * @param organizationAddress the value for CONSIGN_ORGANIZATION.ORGANIZATION_ADDRESS
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setOrganizationAddress(String organizationAddress) {
        this.organizationAddress = organizationAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSIGN_ORGANIZATION.PHONENUM
     *
     * @return the value of CONSIGN_ORGANIZATION.PHONENUM
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public String getPhonenum() {
        return phonenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSIGN_ORGANIZATION.PHONENUM
     *
     * @param phonenum the value for CONSIGN_ORGANIZATION.PHONENUM
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setPhonenum(String phonenum) {
        this.phonenum = phonenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSIGN_ORGANIZATION.POSTCODE
     *
     * @return the value of CONSIGN_ORGANIZATION.POSTCODE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public String getPostcode() {
        return postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSIGN_ORGANIZATION.POSTCODE
     *
     * @param postcode the value for CONSIGN_ORGANIZATION.POSTCODE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSIGN_ORGANIZATION.CREATE_DATE
     *
     * @return the value of CONSIGN_ORGANIZATION.CREATE_DATE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSIGN_ORGANIZATION.CREATE_DATE
     *
     * @param createDate the value for CONSIGN_ORGANIZATION.CREATE_DATE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSIGN_ORGANIZATION.CREATE_USER
     *
     * @return the value of CONSIGN_ORGANIZATION.CREATE_USER
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSIGN_ORGANIZATION.CREATE_USER
     *
     * @param createUser the value for CONSIGN_ORGANIZATION.CREATE_USER
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSIGN_ORGANIZATION.UPDATE_DATE
     *
     * @return the value of CONSIGN_ORGANIZATION.UPDATE_DATE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSIGN_ORGANIZATION.UPDATE_DATE
     *
     * @param updateDate the value for CONSIGN_ORGANIZATION.UPDATE_DATE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSIGN_ORGANIZATION.UPDATE_USER
     *
     * @return the value of CONSIGN_ORGANIZATION.UPDATE_USER
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSIGN_ORGANIZATION.UPDATE_USER
     *
     * @param updateUser the value for CONSIGN_ORGANIZATION.UPDATE_USER
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSIGN_ORGANIZATION.REMARK
     *
     * @return the value of CONSIGN_ORGANIZATION.REMARK
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSIGN_ORGANIZATION.REMARK
     *
     * @param remark the value for CONSIGN_ORGANIZATION.REMARK
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    @Override
	public String toString() {
		return ToStringBuilder.reflectionToString(this, ToStringStyle.MULTI_LINE_STYLE);
	}
}