package com.lims.domain.po;

import java.io.Serializable;

import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

/**
 * 字典项
 * @author lizhihua
 *
 */
public class DictItem extends BaseDomain implements Serializable {
    /**
	 *
	 */
	private static final long serialVersionUID = 1L;

	static final String DICT_ITEM_OTHER_VALUE = "-9999";		//指定字典项中值为"其他"的键值


	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DICT_ITEM.ID
     *
     * @mbggenerated Mon Jun 03 20:16:24 CST 2013
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DICT_ITEM.DICT_INFO_TYPE
     *
     * @mbggenerated Mon Jun 03 20:16:24 CST 2013
     */
    private String dictInfoType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DICT_ITEM.DICT_KEY
     *
     * @mbggenerated Mon Jun 03 20:16:24 CST 2013
     */
    private String dictKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DICT_ITEM.DICT_VALUE1
     *
     * @mbggenerated Mon Jun 03 20:16:24 CST 2013
     */
    private String dictValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DICT_ITEM.ACTIVE_FLAG
     *
     * @mbggenerated Mon Jun 03 20:16:24 CST 2013
     */
    private String activeFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DICT_ITEM.ROOT_FLAG
     *
     * @mbggenerated Mon Jun 03 20:16:24 CST 2013
     */
    private String rootFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DICT_ITEM.PARENT_ID
     *
     * @mbggenerated Mon Jun 03 20:16:24 CST 2013
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DICT_ITEM.DICT_SORT
     *
     * @mbggenerated Mon Jun 03 20:16:24 CST 2013
     */
    private int dictSort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DICT_ITEM.ID
     *
     * @return the value of DICT_ITEM.ID
     *
     * @mbggenerated Mon Jun 03 20:16:24 CST 2013
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DICT_ITEM.ID
     *
     * @param id the value for DICT_ITEM.ID
     *
     * @mbggenerated Mon Jun 03 20:16:24 CST 2013
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DICT_ITEM.DICT_INFO_TYPE
     *
     * @return the value of DICT_ITEM.DICT_INFO_TYPE
     *
     * @mbggenerated Mon Jun 03 20:16:24 CST 2013
     */
    public String getDictInfoType() {
        return dictInfoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DICT_ITEM.DICT_INFO_TYPE
     *
     * @param dictInfoType the value for DICT_ITEM.DICT_INFO_TYPE
     *
     * @mbggenerated Mon Jun 03 20:16:24 CST 2013
     */
    public void setDictInfoType(String dictInfoType) {
        this.dictInfoType = dictInfoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DICT_ITEM.DICT_KEY
     *
     * @return the value of DICT_ITEM.DICT_KEY
     *
     * @mbggenerated Mon Jun 03 20:16:24 CST 2013
     */
    public String getDictKey() {
        return dictKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DICT_ITEM.DICT_KEY
     *
     * @param dictKey the value for DICT_ITEM.DICT_KEY
     *
     * @mbggenerated Mon Jun 03 20:16:24 CST 2013
     */
    public void setDictKey(String dictKey) {
        this.dictKey = dictKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DICT_ITEM.ACTIVE_FLAG
     *
     * @return the value of DICT_ITEM.ACTIVE_FLAG
     *
     * @mbggenerated Mon Jun 03 20:16:24 CST 2013
     */
    public String getActiveFlag() {
        return activeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DICT_ITEM.ACTIVE_FLAG
     *
     * @param activeFlag the value for DICT_ITEM.ACTIVE_FLAG
     *
     * @mbggenerated Mon Jun 03 20:16:24 CST 2013
     */
    public void setActiveFlag(String activeFlag) {
        this.activeFlag = activeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DICT_ITEM.ROOT_FLAG
     *
     * @return the value of DICT_ITEM.ROOT_FLAG
     *
     * @mbggenerated Mon Jun 03 20:16:24 CST 2013
     */
    public String getRootFlag() {
        return rootFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DICT_ITEM.ROOT_FLAG
     *
     * @param rootFlag the value for DICT_ITEM.ROOT_FLAG
     *
     * @mbggenerated Mon Jun 03 20:16:24 CST 2013
     */
    public void setRootFlag(String rootFlag) {
        this.rootFlag = rootFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DICT_ITEM.PARENT_ID
     *
     * @return the value of DICT_ITEM.PARENT_ID
     *
     * @mbggenerated Mon Jun 03 20:16:24 CST 2013
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DICT_ITEM.PARENT_ID
     *
     * @param parentId the value for DICT_ITEM.PARENT_ID
     *
     * @mbggenerated Mon Jun 03 20:16:24 CST 2013
     */
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DICT_ITEM.DICT_SORT
     *
     * @return the value of DICT_ITEM.DICT_SORT
     *
     * @mbggenerated Mon Jun 03 20:16:24 CST 2013
     */
    public int getDictSort() {
        return dictSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DICT_ITEM.DICT_SORT
     *
     * @param dictSort the value for DICT_ITEM.DICT_SORT
     *
     * @mbggenerated Mon Jun 03 20:16:24 CST 2013
     */
    public void setDictSort(int dictSort) {
        this.dictSort = dictSort;
    }

    @Override
	public String toString() {
		return ToStringBuilder.reflectionToString(this, ToStringStyle.MULTI_LINE_STYLE);
	}

	public String getDictValue() {
		return dictValue;
	}

	public void setDictValue(String dictValue) {
		this.dictValue = dictValue;
	}

}