package com.lims.domain.po;

import java.io.Serializable;

import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

/**
 * 字典表
 * @author lizhihua
 *
 */
public class DictInfo extends BaseDomain implements Serializable {
    /**
	 *
	 */
	private static final long serialVersionUID = 1L;


	public static final String CONSIGN_MODE = "CONSIGN_MODE";						//送检方式
	public static final String CHECK_CONTENT = "CHECK_CONTENT";					//检验内容
	public static final String SAMPLE_CARRIER = "SAMPLE_CARRIER";					//样本载体
	public static final String SAMPLE_TYPE = "SAMPLE_TYPE";						//样本类型
	public static final String HOLE_DIAMETER = "HOLE_DIAMETER";					//取样孔径
	public static final String EXAMINE_TYPE = "EXAMINE_TYPE";						//检验类型
	public static final String EXAMINE_STATUS = "EXAMINE_STATUS";					//检验状态
	public static final String PCR_SYSTEM = "PCR_SYSTEM";							//扩增体系
	public static final String PCR_LOOP_COUNT = "PCR_LOOP_COUNT";					//扩增循环数
	public static final String ANALYSIS_INSTRUMENT = "ANALYSIS_INSTRUMENT";		//分析软件类型
	public static final String REVIEW_STATUS = "REVIEW_STATUS";					//复核状态
	public static final String GENDER = "GENDER";								//性别

	public static final String EXAMINE_INSTRUMENT = "EXAMINE_INSTRUMENT";		//检测仪编号

	public static final String UPLOAD_FILE_TYPE = "UPLOAD_FILE_TYPE";

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DICT_INFO.ID
     *
     * @mbggenerated Mon Jun 03 20:14:36 CST 2013
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DICT_INFO.DICT_INFO_TYPE
     *
     * @mbggenerated Mon Jun 03 20:14:36 CST 2013
     */
    private String dictInfoType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DICT_INFO.DICT_INFO_NAME
     *
     * @mbggenerated Mon Jun 03 20:14:36 CST 2013
     */
    private String dictInfoName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DICT_INFO.ID
     *
     * @return the value of DICT_INFO.ID
     *
     * @mbggenerated Mon Jun 03 20:14:36 CST 2013
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DICT_INFO.ID
     *
     * @param id the value for DICT_INFO.ID
     *
     * @mbggenerated Mon Jun 03 20:14:36 CST 2013
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DICT_INFO.DICT_INFO_TYPE
     *
     * @return the value of DICT_INFO.DICT_INFO_TYPE
     *
     * @mbggenerated Mon Jun 03 20:14:36 CST 2013
     */
    public String getDictInfoType() {
        return dictInfoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DICT_INFO.DICT_INFO_TYPE
     *
     * @param dictInfoType the value for DICT_INFO.DICT_INFO_TYPE
     *
     * @mbggenerated Mon Jun 03 20:14:36 CST 2013
     */
    public void setDictInfoType(String dictInfoType) {
        this.dictInfoType = dictInfoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DICT_INFO.DICT_INFO_NAME
     *
     * @return the value of DICT_INFO.DICT_INFO_NAME
     *
     * @mbggenerated Mon Jun 03 20:14:36 CST 2013
     */
    public String getDictInfoName() {
        return dictInfoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DICT_INFO.DICT_INFO_NAME
     *
     * @param dictInfoName the value for DICT_INFO.DICT_INFO_NAME
     *
     * @mbggenerated Mon Jun 03 20:14:36 CST 2013
     */
    public void setDictInfoName(String dictInfoName) {
        this.dictInfoName = dictInfoName;
    }

    @Override
	public String toString() {
		return ToStringBuilder.reflectionToString(this, ToStringStyle.MULTI_LINE_STYLE);
	}
}