package com.lims.domain.po;

import java.io.Serializable;
import java.util.Date;

import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

public class LocusInfo implements Serializable {
    /**
	 *
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOCUS_INFO.ID
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOCUS_INFO.GENONAME
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    private String genoName;

    private String genoAlias;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOCUS_INFO.GENENO
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    private String genoNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOCUS_INFO.GENEDESC
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    private String genoDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOCUS_INFO.CREATE_DATE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOCUS_INFO.CREATE_USER
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOCUS_INFO.UPDATE_DATE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOCUS_INFO.UPDATE_USER
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    private String updateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOCUS_INFO.ID
     *
     * @return the value of LOCUS_INFO.ID
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOCUS_INFO.ID
     *
     * @param id the value for LOCUS_INFO.ID
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOCUS_INFO.CREATE_DATE
     *
     * @return the value of LOCUS_INFO.CREATE_DATE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOCUS_INFO.CREATE_DATE
     *
     * @param createDate the value for LOCUS_INFO.CREATE_DATE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOCUS_INFO.CREATE_USER
     *
     * @return the value of LOCUS_INFO.CREATE_USER
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOCUS_INFO.CREATE_USER
     *
     * @param createUser the value for LOCUS_INFO.CREATE_USER
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOCUS_INFO.UPDATE_DATE
     *
     * @return the value of LOCUS_INFO.UPDATE_DATE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOCUS_INFO.UPDATE_DATE
     *
     * @param updateDate the value for LOCUS_INFO.UPDATE_DATE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOCUS_INFO.UPDATE_USER
     *
     * @return the value of LOCUS_INFO.UPDATE_USER
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOCUS_INFO.UPDATE_USER
     *
     * @param updateUser the value for LOCUS_INFO.UPDATE_USER
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    @Override
	public String toString() {
		return ToStringBuilder.reflectionToString(this, ToStringStyle.MULTI_LINE_STYLE);
	}

	public String getGenoName() {
		return genoName;
	}

	public void setGenoName(String genoName) {
		this.genoName = genoName;
	}

	public String getGenoAlias() {
		return genoAlias;
	}

	public void setGenoAlias(String genoAlias) {
		this.genoAlias = genoAlias;
	}

	public String getGenoNo() {
		return genoNo;
	}

	public void setGenoNo(String genoNo) {
		this.genoNo = genoNo;
	}

	public String getGenoDesc() {
		return genoDesc;
	}

	public void setGenoDesc(String genoDesc) {
		this.genoDesc = genoDesc;
	}
}