package com.lims.domain.po;

import java.util.Date;

import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

public class PcrRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PCR_RECORD.ID
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    private String id;

    private String boardInfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PCR_RECORD.PCR_DATE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    private Date pcrDate;

    private String pcrUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PCR_RECORD.PCR_INSTRUMENT
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    private String pcrInstrument;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PCR_RECORD.TEMPERATURE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    private String temperature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PCR_RECORD.HUMIDITY
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    private String humidity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PCR_RECORD.LOOP_COUNT
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    private String loopCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PCR_RECORD.PCR_SYSTEM
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    private String pcrSystem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PCR_RECORD.REAGENT_NO
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    private String reagentNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PCR_RECORD.EXAMINE_USER
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    private String examineUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PCR_RECORD.EXAMINE_DATE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    private Date examineDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PCR_RECORD.REMARK
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    private String remark;

    private String createUser;

    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PCR_RECORD.ID
     *
     * @return the value of PCR_RECORD.ID
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PCR_RECORD.ID
     *
     * @param id the value for PCR_RECORD.ID
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PCR_RECORD.PCR_DATE
     *
     * @return the value of PCR_RECORD.PCR_DATE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public Date getPcrDate() {
        return pcrDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PCR_RECORD.PCR_DATE
     *
     * @param pcrDate the value for PCR_RECORD.PCR_DATE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setPcrDate(Date pcrDate) {
        this.pcrDate = pcrDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PCR_RECORD.PCR_INSTRUMENT
     *
     * @return the value of PCR_RECORD.PCR_INSTRUMENT
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public String getPcrInstrument() {
        return pcrInstrument;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PCR_RECORD.PCR_INSTRUMENT
     *
     * @param pcrInstrument the value for PCR_RECORD.PCR_INSTRUMENT
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setPcrInstrument(String pcrInstrument) {
        this.pcrInstrument = pcrInstrument;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PCR_RECORD.TEMPERATURE
     *
     * @return the value of PCR_RECORD.TEMPERATURE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public String getTemperature() {
        return temperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PCR_RECORD.TEMPERATURE
     *
     * @param temperature the value for PCR_RECORD.TEMPERATURE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setTemperature(String temperature) {
        this.temperature = temperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PCR_RECORD.HUMIDITY
     *
     * @return the value of PCR_RECORD.HUMIDITY
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public String getHumidity() {
        return humidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PCR_RECORD.HUMIDITY
     *
     * @param humidity the value for PCR_RECORD.HUMIDITY
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setHumidity(String humidity) {
        this.humidity = humidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PCR_RECORD.PCR_SYSTEM
     *
     * @return the value of PCR_RECORD.PCR_SYSTEM
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public String getPcrSystem() {
        return pcrSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PCR_RECORD.PCR_SYSTEM
     *
     * @param pcrSystem the value for PCR_RECORD.PCR_SYSTEM
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setPcrSystem(String pcrSystem) {
        this.pcrSystem = pcrSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PCR_RECORD.REAGENT_NO
     *
     * @return the value of PCR_RECORD.REAGENT_NO
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public String getReagentNo() {
        return reagentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PCR_RECORD.REAGENT_NO
     *
     * @param reagentNo the value for PCR_RECORD.REAGENT_NO
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setReagentNo(String reagentNo) {
        this.reagentNo = reagentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PCR_RECORD.EXAMINE_USER
     *
     * @return the value of PCR_RECORD.EXAMINE_USER
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public String getExamineUser() {
        return examineUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PCR_RECORD.EXAMINE_USER
     *
     * @param examineUser the value for PCR_RECORD.EXAMINE_USER
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setExamineUser(String examineUser) {
        this.examineUser = examineUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PCR_RECORD.EXAMINE_DATE
     *
     * @return the value of PCR_RECORD.EXAMINE_DATE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public Date getExamineDate() {
        return examineDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PCR_RECORD.EXAMINE_DATE
     *
     * @param examineDate the value for PCR_RECORD.EXAMINE_DATE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setExamineDate(Date examineDate) {
        this.examineDate = examineDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PCR_RECORD.REMARK
     *
     * @return the value of PCR_RECORD.REMARK
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PCR_RECORD.REMARK
     *
     * @param remark the value for PCR_RECORD.REMARK
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    @Override
	public String toString() {
		return ToStringBuilder.reflectionToString(this, ToStringStyle.MULTI_LINE_STYLE);
	}

	public String getBoardInfoId() {
		return boardInfoId;
	}

	public void setBoardInfoId(String boardInfoId) {
		this.boardInfoId = boardInfoId;
	}

	public String getCreateUser() {
		return createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getLoopCount() {
		return loopCount;
	}

	public void setLoopCount(String loopCount) {
		this.loopCount = loopCount;
	}

	public String getPcrUser() {
		return pcrUser;
	}

	public void setPcrUser(String pcrUser) {
		this.pcrUser = pcrUser;
	}
}