package com.lims.domain.po;

import java.io.Serializable;
import java.util.Date;

import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

public class PolluteRecord extends BaseDomain implements Serializable {
    /**
	 *
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POLLUTE_RECORD.ID
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POLLUTE_RECORD.QCP_ID
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    private String qcpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POLLUTE_RECORD.MATCHED_SAMPLE_ID
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    private String matchedSampleId;

    private String sampleSourceGeneId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POLLUTE_RECORD.MATCH_DATE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    private Date matchDate;


    private int sameNum;


    private int diffNum;


    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POLLUTE_RECORD.ID
     *
     * @return the value of POLLUTE_RECORD.ID
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POLLUTE_RECORD.ID
     *
     * @param id the value for POLLUTE_RECORD.ID
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POLLUTE_RECORD.QCP_ID
     *
     * @return the value of POLLUTE_RECORD.QCP_ID
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public String getQcpId() {
        return qcpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POLLUTE_RECORD.QCP_ID
     *
     * @param qcpId the value for POLLUTE_RECORD.QCP_ID
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setQcpId(String qcpId) {
        this.qcpId = qcpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POLLUTE_RECORD.MATCHED_SAMPLE_ID
     *
     * @return the value of POLLUTE_RECORD.MATCHED_SAMPLE_ID
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public String getMatchedSampleId() {
        return matchedSampleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POLLUTE_RECORD.MATCHED_SAMPLE_ID
     *
     * @param matchedSampleId the value for POLLUTE_RECORD.MATCHED_SAMPLE_ID
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setMatchedSampleId(String matchedSampleId) {
        this.matchedSampleId = matchedSampleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POLLUTE_RECORD.MATCH_DATE
     *
     * @return the value of POLLUTE_RECORD.MATCH_DATE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public Date getMatchDate() {
        return matchDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POLLUTE_RECORD.MATCH_DATE
     *
     * @param matchDate the value for POLLUTE_RECORD.MATCH_DATE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setMatchDate(Date matchDate) {
        this.matchDate = matchDate;
    }



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POLLUTE_RECORD.REMARK
     *
     * @return the value of POLLUTE_RECORD.REMARK
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POLLUTE_RECORD.REMARK
     *
     * @param remark the value for POLLUTE_RECORD.REMARK
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    @Override
	public String toString() {
		return ToStringBuilder.reflectionToString(this, ToStringStyle.MULTI_LINE_STYLE);
	}

	public int getSameNum() {
		return sameNum;
	}

	public void setSameNum(int sameNum) {
		this.sameNum = sameNum;
	}

	public int getDiffNum() {
		return diffNum;
	}

	public void setDiffNum(int diffNum) {
		this.diffNum = diffNum;
	}

	public String getSampleSourceGeneId() {
		return sampleSourceGeneId;
	}

	public void setSampleSourceGeneId(String sampleSourceGeneId) {
		this.sampleSourceGeneId = sampleSourceGeneId;
	}
}