package com.lims.domain.po;

import java.io.Serializable;
import java.util.Date;

import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

public class ReagentKit extends BaseDomain implements Serializable {
    /**
	 *
	 */
	private static final long serialVersionUID = 1L;

	public static final String LOCUS_ORDER_SEPARATOR = "/";

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REAGENT_KIT.ID
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REAGENT_KIT.REAGENT_NAME
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    private String reagentName;

    private String reagentProducer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REAGENT_KIT.REAGENT_DESC
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    private String reagentDesc;

    private String reagentVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REAGENT_KIT.GENE_ORDER
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    private String locusOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REAGENT_KIT.CREATE_DATE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REAGENT_KIT.CREATE_USER
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    private String createUser;

    private String createUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REAGENT_KIT.UPDATE_DATE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REAGENT_KIT.UPDATE_USER
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    private String updateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REAGENT_KIT.ID
     *
     * @return the value of REAGENT_KIT.ID
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REAGENT_KIT.ID
     *
     * @param id the value for REAGENT_KIT.ID
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REAGENT_KIT.REAGENT_NAME
     *
     * @return the value of REAGENT_KIT.REAGENT_NAME
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public String getReagentName() {
        return reagentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REAGENT_KIT.REAGENT_NAME
     *
     * @param reagentName the value for REAGENT_KIT.REAGENT_NAME
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setReagentName(String reagentName) {
        this.reagentName = reagentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REAGENT_KIT.REAGENT_DESC
     *
     * @return the value of REAGENT_KIT.REAGENT_DESC
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public String getReagentDesc() {
        return reagentDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REAGENT_KIT.REAGENT_DESC
     *
     * @param reagentDesc the value for REAGENT_KIT.REAGENT_DESC
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setReagentDesc(String reagentDesc) {
        this.reagentDesc = reagentDesc;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REAGENT_KIT.CREATE_DATE
     *
     * @return the value of REAGENT_KIT.CREATE_DATE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REAGENT_KIT.CREATE_DATE
     *
     * @param createDate the value for REAGENT_KIT.CREATE_DATE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REAGENT_KIT.CREATE_USER
     *
     * @return the value of REAGENT_KIT.CREATE_USER
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REAGENT_KIT.CREATE_USER
     *
     * @param createUser the value for REAGENT_KIT.CREATE_USER
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REAGENT_KIT.UPDATE_DATE
     *
     * @return the value of REAGENT_KIT.UPDATE_DATE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REAGENT_KIT.UPDATE_DATE
     *
     * @param updateDate the value for REAGENT_KIT.UPDATE_DATE
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REAGENT_KIT.UPDATE_USER
     *
     * @return the value of REAGENT_KIT.UPDATE_USER
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REAGENT_KIT.UPDATE_USER
     *
     * @param updateUser the value for REAGENT_KIT.UPDATE_USER
     *
     * @mbggenerated Thu May 30 19:42:41 CST 2013
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    @Override
	public String toString() {
		return ToStringBuilder.reflectionToString(this, ToStringStyle.MULTI_LINE_STYLE);
	}

	public String getCreateUserName() {
		return createUserName;
	}

	public void setCreateUserName(String createUserName) {
		this.createUserName = createUserName;
	}

	public String getReagentProducer() {
		return reagentProducer;
	}

	public void setReagentProducer(String reagentProducer) {
		this.reagentProducer = reagentProducer;
	}

	public String getLocusOrder() {
		return locusOrder;
	}

	public void setLocusOrder(String locusOrder) {
		this.locusOrder = locusOrder;
	}

	public String getReagentVersion() {
		return reagentVersion;
	}

	public void setReagentVersion(String reagentVersion) {
		this.reagentVersion = reagentVersion;
	}
}