package com.lims.domain.po;

import java.io.Serializable;
import java.util.Date;

import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

public class SampleInfo extends BaseDomain implements Serializable {
    /**
	 *
	 */
	private static final long serialVersionUID = 1L;


	public static final String EXAMINE_STATUS_WAITING = "1";			//未开始
	public static final String EXAMINE_STATUS_PROCESSING = "2";			//进行中
	public static final String EXAMINE_STATUS_FINISHED = "3";			//已完成



	public static final String ACCEPT_STATUS_WAITING = "0";			//未受理
	public static final String ACCEPT_STATUS_ACCEPTED = "1";			//已受理
	public static final String ACCEPT_STATUS_REJECT = "9";			//拒绝受理

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SAMPLE_INFO.SAMPLE_ID
     *
     * @mbggenerated Thu May 30 20:01:12 CST 2013
     */
    protected String id;

    protected String consignmentId;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SAMPLE_INFO.SAMPLE_NAME
     *
     * @mbggenerated Thu May 30 20:01:12 CST 2013
     */
    protected String sampleName;

    protected String sampleNo;

    protected String sampleDesc;

    protected Date createDate;

    protected String createUser;

    protected String remark;

    /** 受理状态 */
    protected String acceptStatus;
    /** 受理时间 */
    protected Date acceptDate;
    /** 受理人 */
    protected String acceptUser;

    protected Date updateDate;

    protected String updateUser;


    @Override
	public String toString() {
		return ToStringBuilder.reflectionToString(this, ToStringStyle.MULTI_LINE_STYLE);
	}


	public String getId() {
		return id;
	}


	public void setId(String id) {
		this.id = id;
	}


	public String getSampleName() {
		return sampleName;
	}


	public void setSampleName(String sampleName) {
		this.sampleName = sampleName;
	}


	public String getSampleNo() {
		return sampleNo;
	}


	public void setSampleNo(String sampleNo) {
		this.sampleNo = sampleNo;
	}


	public String getSampleDesc() {
		return sampleDesc;
	}


	public void setSampleDesc(String sampleDesc) {
		this.sampleDesc = sampleDesc;
	}


	public Date getCreateDate() {
		return createDate;
	}


	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}


	public String getCreateUser() {
		return createUser;
	}


	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}


	public String getRemark() {
		return remark;
	}


	public void setRemark(String remark) {
		this.remark = remark;
	}


	public String getConsignmentId() {
		return consignmentId;
	}


	public void setConsignmentId(String consignmentId) {
		this.consignmentId = consignmentId;
	}


	public String getAcceptStatus() {
		return acceptStatus;
	}


	public void setAcceptStatus(String acceptStatus) {
		this.acceptStatus = acceptStatus;
	}


	public Date getAcceptDate() {
		return acceptDate;
	}


	public void setAcceptDate(Date acceptDate) {
		this.acceptDate = acceptDate;
	}


	public String getAcceptUser() {
		return acceptUser;
	}


	public void setAcceptUser(String acceptUser) {
		this.acceptUser = acceptUser;
	}


	public Date getUpdateDate() {
		return updateDate;
	}


	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}


	public String getUpdateUser() {
		return updateUser;
	}


	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}



}